# Generated by Django 3.0.3 on 2020-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_info',
            },
        ),
    ]
